### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by camchardukian** [alphacrutch/Box-Creator-HTML-CSS-JS#1]
Hey man, I love that you included a a descriptive README.md in this repository. For the CSS, I think your code would look more professional if you checked the formatting more carefully (indents, consistent spacing, etc).

It may also be beneficial to learn more about nesting your CSS rules for future projects with larger code bases. On the JavaScript side, I'd recommend using const or let instead of var. This will show potential employers that you're up to date with ES6+ coding standards.

I'd also reword your alert message lol.

Overall, however, I thought you did an excellent job considering this was your first project! The things I pointed out above are relatively minor, and you should be proud of yourself for having built this! :D

**Comment by alphacrutch** [comment]
I really appreciate the feedback. Your the first person to give feedback. I
will definitely use all that you mentioned in future projects. All I was
thinking was keep it simple make it work. Lol . I do have major project I
am working on it's a tall leap but I believe I can make it once I acquired
the knowledge on the relevant technologies I will be using. I basically
want to build a catalogue application.
